---
title: "Research overview"
---

I'm a social-ecological systems researcher, with an interdisciplinary approach developed through training in earth systems and aquatic ecology (BSc 2008-12), with specialisation in water science, policy and management (MSc 2015-16) and the health impacts of water insecurity (DPhil 2017-21). My research aims to support policy that advances human health equity and ecosystem integrity through better management of water quality risks.

Water quality challenges are inadequately considered in key agendas and policy instruments globally – including those that focus on drinking water services, biodiversity restoration, energy sector transformation, and climate change adaptation. With water demand and pollution risks compounding as climate change intensifies the water cycle, complex pressures are causing severe harm to people and ecosystems. One in four people lack sustained access to safe water and strong inequalities persist, including through systemic exclusions in higher-income countries. Contaminated water is also driving biodiversity decline, with a quarter of critically endangered species living in freshwater habitats.

To manage the compound risks of water insecurity, there is a pressing need for analysis that reconciles models of ideal water management decision-making with actual decision-making. My research cuts across academic disciplines (and quantitative and qualitative methods) so that I can explore the systemic links between water quality data and decision-making. With systems thinking and collaboration central in my approach, I have three key intersecting research themes:

### Innovation for water quality risk assessment

This research progresses understandings of water quality risk assessment and treatment approaches, with a view to both technical and institutional effectiveness. From collaborations that I led with the British Geological Survey and the Kenya Medical Research Institute I have published work on [tryptophan-like fluorescence](https://www.sciencedirect.com/science/article/abs/pii/S0048969718327700) and [*Escherichia coli*](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0245910)as microbial water quality indicators. Linking data to decision-making and proactive planning, I co-authored [a framework for monitoring the safety of water services](https://www.nature.com/articles/s41545-020-00083-1) and a synthesis of prospects for advancing ambient water quality monitoring through citizen science (article under review).

### Leveraging data for social-ecological transformation

This research seeks to understand the role of information feedbacks in changing human-environment interactions. I’ve investigated [how water quality monitoring influences stakeholder cooperation on water service delivery](https://www.nature.com/articles/s41545-020-0062-x)in rural Kenya and identified [reinforcing feedbacks for sustained use of decentralised water treatment technologies](https://pubs.acs.org/doi/10.1021/acsestwater.3c00779). Ongoing work in this area, which can be characterised as implementation science applied through science-practitioner partnerships, includes piloting [results-based funding for safe water services](https://reachwater.uk/resource/results-based-funding-for-safe-drinking-water-services/), establishing fit-for-purpose labs to support rural water safety planning, and developing guidance for sustaining decentralised drinking water treatment activities.

### Reducing inequalities in water quality risk

This research responds to the sustainable development commitment to ‘leave no one behind’ and the imperative of all research to follow ethical principles. I have published on the [importance of understanding poverty threatscapes and gender norms when including water quality risk reporting in development efforts](https://www.mdpi.com/1660-4601/19/1/597). Building on this work, I am leading a study of water safety perception and practice as part of a mixed-methods research programme on intrahousehold decision-making and water (in)security in urban, peri-urban and rural areas of Ethiopia, Kenya and Bangladesh. Beyond my own research, I am one of the academic leads on research ethics teaching at Oxford's School of Geography and the Environment. Alongside Dr Ariell Ahearn and Dr Catherine Grasham, I co-lead a research ethics workshop for all MSc and first-year DPhil students, for which I focus on public and stakeholder engagement, publication ethics, and data sharing ethics.

### Advisory roles

Alongside my main research activities, I am currently providing advisory support to:

-   Uptime Global on results-based funding for safe water services

-   Segura Advanced Water Testing Ltd on development of electrochemical water quality test methods for rapid measurement of *E. coli* and heavy-metals

-   Aquaya Institute on water quality data sharing for the WaterTRACS project
