---
title: "Publications"
---

## Peer-reviewed

\(2024\) Reinforcing feedbacks for sustainable implementation of rural drinking-water treatment technology. *ACS ES&T Water.* Laauwen M and **Nowicki S**. \[[view online](https://doi.org/10.1021/acsestwater.3c00779)\] \[[download PDF](Paper2024_ReinforcingTreatment.pdf)\]

\(2023\) Water chemistry poses health risks as reliance on groundwater increases: a systematic review of hydrogeochemistry research from Ethiopia and Kenya. *Science of the Total Environment.* **Nowicki S**, Birhanu B, Tanui F, Sule MN, Charles K, Olago D, and Kebede S. \[[view online](https://doi.org/10.1016/j.scitotenv.2023.166929)\] \[[download PDF](Paper2023_GroundwaterChemistry.pdf)\]

\(2022\) Fear, efficacy, and environmental health risk reporting: complex responses to water quality test results in low-income communities. *International Journal of Environmental Research and Public Health*. **Nowicki S**, Bukachi S, Hoque S, Katuva J, Musyoka M, Sammy M, Mwaniki M, Omia D, Wambua F, and Charles, K. \[[view online](https://doi.org/10.3390/ijerph19010597)\] \[[download PDF](Paper2022_FearResults.pdf)\]

\(2021\) The utility of *Escherichia coli* as a contamination indicator for rural drinking water: evidence from whole genome sequencing. *PLoS ONE.* **Nowicki S**, deLaurent ZR, de Villiers EP, Githinji G, and Charles KJ. \[[view online](https://doi.org/10.1371/journal.pone.0245910)\] \[[download PDF](Paper2021_EcoliSequencing.pdf)\]

\(2020\) Including water quality monitoring in rural water services: why safe water requires challenging the quantity versus quality dichotomy. *npj Clean Water.* **Nowicki S**, Koehler J, and Charles KJ. \[[view online](https://doi.org/10.1038/s41545-020-0062-x)\] \[[download PDF](Paper2020_IncludingQuality.pdf)\]

\(2020\) A framework for monitoring the safety of water services: from measurements to security. *npj Clean Water*. Charles KJ, **Nowicki S**, and Bartram JK. \[[view online](https://doi.org/10.1038/s41545-020-00083-1)\] \[[download PDF](Paper2020_Framework.pdf)\]

\(2019\) Tryptophan-like fluorescence as a measure of microbial contamination risk in groundwater. *Science of The Total Environment*. **Nowicki S**, Lapworth DJ, Ward JST, Thomson P, and Charles K. \[[view online](https://doi.org/10.1016/j.scitotenv.2018.07.274)\] \[[download PDF](Paper2019_TLF.pdf)\]

## Book chapters

\(2020\) Water and Health: A Dynamic, Enduring Challenge. In: Water Science, Policy, and Management: A Global Challenge. John Wiley & Sons Ltd.; p. 97–116. Charles KJ, **Nowicki S**, Thomson P, Bradley DJ. \[[view online](https://www.wiley.com/en-us/Water+Science%2C+Policy+and+Management%3A+A+Global+Challenge-p-9781119520658)\] \[[download PDF](Chapter2020_Health.pdf)\]

\(2020\) Wastewater: From a Toxin to a Valuable Resource. In: Water Science, Policy, and Management: A Global Challenge. John Wiley & Sons Ltd.; p. 291–307. Johnstone DWM, **Nowicki S**, Narayan AS, Sinha R. \[[view online](https://www.wiley.com/en-us/Water+Science%2C+Policy+and+Management%3A+A+Global+Challenge-p-9781119520658)\] \[[download PDF](Chapter2020_Wastewater.pdf)\]

## Technical reports and working papers

\(2024\) Opportunities to advance water safety through regulation of rural water services. Discussion document: December 2023. University of Oxford, DWI, Eawag, Government of Bangladesh, Hysawa, Uptime Global, Wasreb, and WHO. Oxford, UK. \[[view online](https://reachwater.uk/resource/opportunities-to-advance-water-safety-through-regulation-of-rural-water-services/)\] \[[download PDF](Brief2024_Regulation.pdf)\]

\(2023\) Results-based funding for safe drinking water services: How a standard contract design with payment for results can accelerate safe drinking water services at scale. REACH working paper 13. University of Oxford and Uptime Global. Oxford, UK. \[[view online](https://reachwater.uk/resource/results-based-funding-for-safe-drinking-water-services/)\] \[[download PDF](Report2023_RBF.pdf)\]

\(2023\) SafePani: Improving drinking water safety for schools and healthcare centres in Khulna district, Bangladesh. Briefing note: January 2023. University of Oxford, Government of Bangladesh, UNICEF, and Hysawa. Oxford, UK. \[[view online](https://reachwater.uk/resource/safepani-improving-drinking-water-safety-for-schools-and-healthcare-centres-in-khulna-district-bangladesh-2/)\] \[[download PDF](Brief2023_SafePani.pdf)\]

\(2021\) Bangladesh Multiple Indicator Cluster Survey 2018-2019, Water Quality Thematic Report. icddr,b, UNICEF, University of Oxford and University of Dhaka. Dhaka, Bangladesh: Bangladesh Bureau of Statistics and UNICEF. \[[view online](https://reachwater.uk/resource/drinking-water-quality-in-bangladesh-2021-updates/)\] \[[download PDF](Report2021_MICS.pdf)\]

\(2021\) Global prospects to deliver safe drinking water services for 100 million rural people by 2030. REACH Working Paper 12. RWSN and University of Oxford. Oxford, UK. \[[view online](https://reachwater.uk/resource/global-prospects-to-deliver-safe-drinking-water-services-for-100-million-rural-people-by-2030/)\] \[[download PDF](Report2021_Global.pdf)\]

\(2021\) Policy reform to deliver safely managed drinking water services for schools in rural Bangladesh. REACH Working Paper 11. University of Oxford and UNICEF. Oxford, UK.

\(2020\) Delivering safely-managed water to schools in Kenya. REACH Working Paper 8. University of Oxford. Oxford, UK.

\(2018\) Developing a Global Compendium on Water Quality Guidelines. IWRA, the French National Office of Water and Aquatic Environments, and the World Water Council. Online.

(2018) Assessing microbiological contamination in groundwater: Field note on using Tryptophan-like Fluorescence (TLF). British Geological Survey Open Report 18/042. Wallingford, UK
